spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://cc.crnv58a7zwkg.ap-northeast-2.rds.amazonaws.com:3306/cc
    username: root
    password: hunil3751

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: ture
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging.level:
  org.hibernate.SQL: debug