spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/cc
    username: root
    password: hunil3751

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: ture

logging.level:
  org.hibernate.SQL: debug